### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by programadoramauri** [programadoramauri/minedownloader#1]
#Hacking
- [ ] Capturar o formato de url

#Códigos
- [ ] Gerador de perfil no minecraft
- [ ] Leitor de json
- [ ] Gerador de url
- [ ] Abrir arquivo zip
